GET http://localhost:3001/places?text=av governador valadares, betim, 1000

###
GET http://localhost:3001/places?text=av amazonas, belo horizonte, 1000
###
@originId = EkBBdi4gR292LiBWYWxhZGFyZXMsIDEwMDAgLSBDZW50cm8sIEJldGltIC0gTUcsIDM2NDEwLTAyNiwgQnJhc2lsIjESLwoUChIJqWNAFJLDpgARpsy5kCM5OC8Q6AcqFAoSCXkSTsuRw6YAETPuVaoFp4Tx

@destinationId = ChIJPUqddeKZpgARusD9CDpIBDQ

###
GET http://localhost:3001/directions?originId={{originId}}&destinationId={{destinationId}} 

###

POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{destinationId}}"
}

###
POST http://localhost:3000/routes/6790ef4aedf75abacd13fa2b/start

###
GET http://localhost:3001/routes

###
GET http://localhost:3001/routes/6758b5813cb3552c2a8d9243